<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.props" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.props" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.15.osoe-1208" />

  <PropertyGroup>
    <Title>Lombiq Vue.js module for Orchard Core - Resources</Title>
    <CopyrightYear>2019</CopyrightYear>
    <DescriptionBody>Adds some Vue.js 3 packages to Orchard Core as ES Modules.</DescriptionBody>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Vue.js</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Vue.js</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Vue.js/blob/dev/Lombiq.VueJs.Resources/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <Import Condition="'$(NuGetBuild)' != 'true'" Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.OrchardCore.Module.Sdk/Sdk/Import.targets" />
  <Import Condition="'$(NuGetBuild)' == 'true'" Project="Sdk.targets" Sdk="Lombiq.MSBuild.OrchardCore.Module.Sdk" Version="1.0.1-alpha.15.osoe-1208" />
</Project>
