<Project Sdk="Microsoft.NET.Sdk.Razor">

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.props"
          Condition="'$(NuGetBuild)' != 'true'"/>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <DefaultItemExcludes>$(DefaultItemExcludes);.git*</DefaultItemExcludes>
  </PropertyGroup>

  <PropertyGroup>
    <Title>Lombiq Vue.js module for Orchard Core - Resources</Title>
    <Authors>Lombiq Technologies</Authors>
    <Copyright>Copyright © 2019, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Vue.js module for Orchard Core - Resources: Adds some Vue.js 3 packages to Orchard Core as ES Modules.</Description>
    <PackageIcon>NuGetIcon.png</PackageIcon>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Vue.js</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Vue.js</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Vue.js/blob/dev/Lombiq.VueJs.Resources/Readme.md</PackageProjectUrl>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OrchardCore.Module.Targets" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="NuGetIcon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' != 'true'">
    <ProjectReference Include="..\..\..\Libraries\Lombiq.HelpfulLibraries\Lombiq.HelpfulLibraries.OrchardCore\Lombiq.HelpfulLibraries.OrchardCore.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(NuGetBuild)' == 'true'">
    <PackageReference Include="Lombiq.HelpfulLibraries.OrchardCore" Version="12.5.0" />
    <PackageReference Include="Lombiq.MSBuild.LibMan.Targets" Version="1.0.0-alpha.6.nest-643" />
    <PackageReference Include="Lombiq.HelpfulLibraries.Attributes" Version="12.5.0" OutputItemType="Analyzer" ReferenceOutputAssembly="true" />
    <PackageReference Include="Lombiq.HelpfulLibraries.SourceGenerators" Version="12.5.0" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true'"/>

</Project>
