<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <ImportLombiqHelpfulLibrariesOrchardCore>true</ImportLombiqHelpfulLibrariesOrchardCore>
  </PropertyGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.props"
          Condition="'$(NuGetBuild)' != 'true' "/>

  <PropertyGroup>
    <Title>Lombiq Vue.js module for Orchard Core - Resources</Title>
    <Copyright>Copyright © 2019, Lombiq Technologies Ltd.</Copyright>
    <Description>Lombiq Vue.js module for Orchard Core - Resources: Adds some Vue.js 3 packages to Orchard Core as ES Modules.</Description>
    <PackageTags>OrchardCore;Lombiq;AspNetCore;Vue.js</PackageTags>
    <RepositoryUrl>https://github.com/Lombiq/Orchard-Vue.js</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Lombiq/Orchard-Vue.js/blob/dev/Lombiq.VueJs.Resources/Readme.md</PackageProjectUrl>
  </PropertyGroup>

  <Import Project="../../../Utilities/Lombiq.MSBuild.Targets/Lombiq.MSBuild.LibMan.Targets/Lombiq.MSBuild.LibMan.Targets.targets"
          Condition="'$(NuGetBuild)' != 'true' "/>

</Project>
